### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [damnmrg/grid-template-init-project#1]
1)
невалидный код
![image](https://user-images.githubusercontent.com/8464662/120320818-48d5b400-c2eb-11eb-9e17-376aea9b0e1f.png)

2)
невалидный стиль
![image](https://user-images.githubusercontent.com/8464662/120320960-6acf3680-c2eb-11eb-9fac-4e43ab3a7366.png)

3)
в html5 нет такого синтаксиса
![image](https://user-images.githubusercontent.com/8464662/120320857-5428df80-c2eb-11eb-90c3-db8b0ef324fb.png)

4)
отступы не соответствуют макету
![image](https://user-images.githubusercontent.com/8464662/120320622-1035da80-c2eb-11eb-9551-b97516add166.png)

5)
не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/120320653-188e1580-c2eb-11eb-9adb-497e9f527b6c.png)

6)
шрифт не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/120320693-20e65080-c2eb-11eb-8c98-d3d9dc371801.png)

7)
не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/120320736-2d6aa900-c2eb-11eb-9bd4-a97374049f37.png)

**Comment by damnmrg** [comment]
https://github.com/damnmrg/grid-template-init-project.git <https://github.com/damnmrg/grid-template-init-project.git>

https://damnmrg.github.io/grid-template-init-project/ <https://damnmrg.github.io/grid-template-init-project/>

**Comment by Alecto** [comment]
7 - не исправлено


8)
требования к высоте блоков не выполнено
![image](https://user-images.githubusercontent.com/8464662/121860046-212a1700-cd01-11eb-9a81-3cb064a32e02.png)
9)
размер шрифта не соотвествует задаче

регистр?
![image](https://user-images.githubusercontent.com/8464662/121860201-4a4aa780-cd01-11eb-8fbb-730336d87cca.png)

**Comment by Alecto** [comment]
https://github.com/damnmrg/grid-template-init-project/issues/1

**Comment by damnmrg** [comment]
извините, не могу понять в чем ошибка 7 пункта. цвет букв для ввода исправила. не подскажете что не так?

Отправлено с iPhone

**Comment by Alecto** [comment]
пн, 14 июн. 2021 г. в 17:38, damnmrg ***@***.***>:

> извините, не могу понять в чем ошибка 7 пункта. цвет букв для ввода
> исправила. не подскажете что не так?

все и сразу: и цвет, и рамка и наведение и фокус - все проверяйте.
для проверка всегда 2 ссылки.

**Comment by damnmrg** [comment]
https://github.com/damnmrg/grid-template-init-project.git <https://github.com/damnmrg/grid-template-init-project.git>

https://damnmrg.github.io/grid-template-init-project/ <https://damnmrg.github.io/grid-template-init-project/>

**Comment by Alecto** [comment]
10)
форматирование кода не выполнено


11)
не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/122336712-f11f8580-cf45-11eb-92a5-2119a1f16c35.png)

**Comment by damnmrg** [comment]
не подскажете что здесь надо исправить? изменить шрифт?

**Comment by Alecto** [comment]
выполните попиксельно сравнение, все отличия прекрасно видны.

>
